import { BaseMinimalEntity } from "src/common/entities/base-minimal.entity";
import { User } from "src/users/entities/user.entity";
import { Column, Entity, ManyToOne } from "typeorm";

// Settings keys for all services
export enum SettingsKeyEnum {
  TRANSLATION_MULTILINGUAL = "TRANSLATION_MULTILINGUAL",
  TRANSLATION_DEFAULT_LANG = "TRANSLATION_DEFAULT_LANG",

  SMS_PROVIDER = "SMS_PROVIDER",
  SMS_ORIGINATOR = "SMS_ORIGINATOR",
  SMS_API_KEY = "SMS_API_KEY",
  SMS_VERIFICATION_CODE_PATTERN = "SMS_VERIFICATION_CODE_PATTERN",
  SMS_BIRTHDAY_CONGRATS = "SMS_BIRTHDAY_CONGRATS",
  SMS_BIRTHDAY_CONGRATS_TIME = "SMS_BIRTHDAY_CONGRATS_TIME",

  EMAIL_NEWSLETTER_SEND = "EMAIL_NEWSLETTER_SEND",
  EMAIL_NEWSLETTER_SEND_TIME = "EMAIL_NEWSLETTER_SEND_TIME",
  EMAIL_NEWSLETTER_HEADER = "EMAIL_NEWSLETTER_HEADER",
  EMAIL_NEWSLETTER_BODY = "EMAIL_NEWSLETTER_BODY",
  EMAIL_NEWSLETTER_FOOTER = "EMAIL_NEWSLETTER_FOOTER",

  COMMENT_IS_APPROVED = "COMMENT_IS_APPROVED",
  COMMENT_FORBIDDEN_EXPRESSIONS = "COMMENT_FORBIDDEN_EXPRESSIONS",
  COMMENT_FORBIDDEN_SUSPEND = "COMMENT_FORBIDDEN_SUSPEND",
  COMMENT_MAX_LENGTH = "COMMENT_MAX_LENGTH",

  ATTACHMENT_URL_EXP_HOURS = "ATTACHMENT_URL_EXPIRATION"
}

export enum SettingsServiceEnum {
  ACTIVITIES = "ACTIVITIES",
  LANGS = "LANGS",
  ATTACHMENTS = "ATTACHMENTS",
  AUTH = "AUTH",
  POSTS = "POSTS",
  POST_COMMENTS = "POST_COMMENTS",
  TAXONOMIES = "TAXONOMIES",
  SMS = "SMS",
  EMAIL = "EMAIL"
}

@Entity()
export class Setting extends BaseMinimalEntity {
  @Column()
  key: SettingsKeyEnum;

  @Column()
  value: string;

  @Column()
  service: SettingsServiceEnum;

  @ManyToOne( () => User )
  updatedBy?: User;
}
